"use strict";(self.webpackChunksailpoint_developer_portal=self.webpackChunksailpoint_developer_portal||[]).push([["612672"],{332912:function(n,e,t){t.r(e),t.d(e,{assets:()=>p,contentTitle:()=>a,default:()=>d,frontMatter:()=>s,metadata:()=>i,toc:()=>l});var i=t(750188),o=t(785893),r=t(250065);let s={id:"python-sdk-error-handling",title:"Error handling with The Python SDK",pagination_label:"Error Handling",sidebar_label:"Error Handling",sidebar_position:8,sidebar_class_name:"pythonsdk",keywords:["py","python","sdk","error"],description:"Learn how to configure error handling when using the Python SDK.",slug:"/tools/sdk/python/error-handling",tags:["SDK"]},a=void 0,p={},l=[];function c(n){let e={code:"code",p:"p",pre:"pre",...(0,r.a)(),...n.components};return(0,o.jsxs)(o.Fragment,{children:[(0,o.jsxs)(e.p,{children:["The Python SDK returns key exceptions if the request fails. You can find these exceptions at ",(0,o.jsx)(e.code,{children:"sailpoint.v3.exceptions"}),"."]}),"\n",(0,o.jsxs)(e.p,{children:["Here is an example of the error handling process. In this example, ",(0,o.jsx)(e.code,{children:'name rt "Test"'})," isn't a valid filter, which causes the function to return a 400 'bad request' exception message. Line 11 will catch that 'bad request' response, and you can log the appropriate message. This example will also catch 401 'unauthorized' and 500 'service exception' messages:"]}),"\n",(0,o.jsx)(e.pre,{children:(0,o.jsx)(e.code,{className:"language-python",metastring:"showLineNumbers",children:'import sailpoint\nimport sailpoint.v3\nfrom sailpoint.configuration import Configuration\nfrom sailpoint.v3.exceptions import BadRequestException, UnauthorizedException, ServiceException\n\nconfiguration = Configuration()\napi_client = sailpoint.v3.ApiClient(configuration)\n\ntry:\n    transforms = sailpoint.v3.TransformsApi(api_client).list_transforms(filters=\'name rt "Test"\')\nexcept BadRequestException as e:\n    print("Exception when calling TransformsApi->list_transforms: %s\\n" % e)\nexcept UnauthorizedException as e:\n    print("Unauthorized exception when calling TransformsApi->list_transforms: %s\\n" % e)\nexcept ServiceException as e:\n    print("Service exception when calling TransformsApi->list_transforms: %s\\n" % e)\n'})}),"\n",(0,o.jsxs)(e.p,{children:["If you don't want the program to exit for any error response, you can include ",(0,o.jsx)(e.code,{children:"pass"})," in each of your ",(0,o.jsx)(e.code,{children:"except"})," blocks after printing the error message, as you can see in this example:"]}),"\n",(0,o.jsx)(e.pre,{children:(0,o.jsx)(e.code,{className:"language-python",children:'import sailpoint\nimport sailpoint.v3\nfrom sailpoint.configuration import Configuration\nfrom sailpoint.v3.exceptions import BadRequestException, UnauthorizedException, ServiceException\n\nconfiguration = Configuration()\napi_client = sailpoint.v3.ApiClient(configuration)\n\ntry:\n    transforms = sailpoint.v3.TransformsApi(api_client).list_transforms(filters=\'name rt "Test"\')\nexcept BadRequestException as e:\n    print("Exception when calling TransformsApi->list_transforms: %s\\n" % e)\n    pass\nexcept UnauthorizedException as e:\n    print("Unauthorized exception when calling TransformsApi->list_transforms: %s\\n" % e)\n    pass\nexcept ServiceException as e:\n    print("Service exception when calling TransformsApi->list_transforms: %s\\n" % e)\n    pass\n'})})]})}function d(n={}){let{wrapper:e}={...(0,r.a)(),...n.components};return e?(0,o.jsx)(e,{...n,children:(0,o.jsx)(c,{...n})}):c(n)}},250065:function(n,e,t){t.d(e,{Z:()=>a,a:()=>s});var i=t(667294);let o={},r=i.createContext(o);function s(n){let e=i.useContext(r);return i.useMemo(function(){return"function"==typeof n?n(e):{...e,...n}},[e,n])}function a(n){let e;return e=n.disableParentContext?"function"==typeof n.components?n.components(o):n.components||o:s(n.components),i.createElement(r.Provider,{value:e},n.children)}},750188:function(n){n.exports=JSON.parse('{"id":"tools/sdk/python/python-sdk-error-handling","title":"Error handling with The Python SDK","description":"Learn how to configure error handling when using the Python SDK.","source":"@site/docs/tools/sdk/python/error-handling.md","sourceDirName":"tools/sdk/python","slug":"/tools/sdk/python/error-handling","permalink":"/docs/tools/sdk/python/error-handling","draft":false,"unlisted":false,"editUrl":"https://github.com/sailpoint-oss/developer.sailpoint.com/edit/main/docs/tools/sdk/python/error-handling.md","tags":[{"inline":true,"label":"SDK","permalink":"/docs/tags/sdk"}],"version":"current","lastUpdatedBy":"darrell-thobe-sp","lastUpdatedAt":1746721553000,"sidebarPosition":8,"frontMatter":{"id":"python-sdk-error-handling","title":"Error handling with The Python SDK","pagination_label":"Error Handling","sidebar_label":"Error Handling","sidebar_position":8,"sidebar_class_name":"pythonsdk","keywords":["py","python","sdk","error"],"description":"Learn how to configure error handling when using the Python SDK.","slug":"/tools/sdk/python/error-handling","tags":["SDK"]},"sidebar":"openApiSidebar","previous":{"title":"Retries","permalink":"/docs/tools/sdk/python/retries"},"next":{"title":"Reference","permalink":"/docs/tools/python/reference"}}')}}]);